packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^6.0.0
  vue: ^3.5.40
  vue-router: ^5.2.0
  "@module-federation/vite": ^1.19.1

# trustPolicy: no-downgrade
minimumReleaseAge: 0
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
  lefthook: true
  vue-demi: true
